/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as PpdbRouteImport } from './routes/ppdb'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnouncementsIndexRouteImport } from './routes/announcements.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProfileVisionRouteImport } from './routes/profile.vision'
import { Route as ProfileStructureRouteImport } from './routes/profile.structure'
import { Route as ProfileHistoryRouteImport } from './routes/profile.history'
import { Route as NewsSchoolRouteImport } from './routes/news.school'
import { Route as NewsAnnouncementsRouteImport } from './routes/news.announcements'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as AnnouncementsSlugRouteImport } from './routes/announcements.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPpdbRouteImport } from './routes/admin.ppdb'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminFacilitiesRouteImport } from './routes/admin.facilities'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAchievementsRouteImport } from './routes/admin.achievements'
import { Route as NewsAnnouncementsIndexRouteImport } from './routes/news.announcements.index'
import { Route as NewsAnnouncementsSlugRouteImport } from './routes/news.announcements.$slug'

const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const PpdbRoute = PpdbRouteImport.update({
  id: '/ppdb',
  path: '/ppdb',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsIndexRoute = AnnouncementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnnouncementsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileVisionRoute = ProfileVisionRouteImport.update({
  id: '/profile/vision',
  path: '/profile/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileStructureRoute = ProfileStructureRouteImport.update({
  id: '/profile/structure',
  path: '/profile/structure',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHistoryRoute = ProfileHistoryRouteImport.update({
  id: '/profile/history',
  path: '/profile/history',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSchoolRoute = NewsSchoolRouteImport.update({
  id: '/news/school',
  path: '/news/school',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsAnnouncementsRoute = NewsAnnouncementsRouteImport.update({
  id: '/news/announcements',
  path: '/news/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsSlugRoute = AnnouncementsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AnnouncementsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/admin/teachers',
  path: '/admin/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPpdbRoute = AdminPpdbRouteImport.update({
  id: '/admin/ppdb',
  path: '/admin/ppdb',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/admin/news',
  path: '/admin/news',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/admin/homepage',
  path: '/admin/homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/admin/hero',
  path: '/admin/hero',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/admin/gallery',
  path: '/admin/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacilitiesRoute = AdminFacilitiesRouteImport.update({
  id: '/admin/facilities',
  path: '/admin/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAchievementsRoute = AdminAchievementsRouteImport.update({
  id: '/admin/achievements',
  path: '/admin/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsAnnouncementsIndexRoute = NewsAnnouncementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsAnnouncementsRoute,
} as any)
const NewsAnnouncementsSlugRoute = NewsAnnouncementsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsAnnouncementsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/ppdb': typeof PpdbRoute
  '/teachers': typeof TeachersRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/ppdb': typeof AdminPpdbRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/announcements': typeof NewsAnnouncementsRouteWithChildren
  '/news/school': typeof NewsSchoolRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/structure': typeof ProfileStructureRoute
  '/profile/vision': typeof ProfileVisionRoute
  '/admin/': typeof AdminIndexRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/news/announcements/$slug': typeof NewsAnnouncementsSlugRoute
  '/news/announcements/': typeof NewsAnnouncementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/ppdb': typeof PpdbRoute
  '/teachers': typeof TeachersRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/ppdb': typeof AdminPpdbRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/school': typeof NewsSchoolRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/structure': typeof ProfileStructureRoute
  '/profile/vision': typeof ProfileVisionRoute
  '/admin': typeof AdminIndexRoute
  '/announcements': typeof AnnouncementsIndexRoute
  '/news/announcements/$slug': typeof NewsAnnouncementsSlugRoute
  '/news/announcements': typeof NewsAnnouncementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/ppdb': typeof PpdbRoute
  '/teachers': typeof TeachersRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/ppdb': typeof AdminPpdbRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/announcements': typeof NewsAnnouncementsRouteWithChildren
  '/news/school': typeof NewsSchoolRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/structure': typeof ProfileStructureRoute
  '/profile/vision': typeof ProfileVisionRoute
  '/admin/': typeof AdminIndexRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/news/announcements/$slug': typeof NewsAnnouncementsSlugRoute
  '/news/announcements/': typeof NewsAnnouncementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/announcements'
    | '/facilities'
    | '/gallery'
    | '/ppdb'
    | '/teachers'
    | '/admin/achievements'
    | '/admin/announcements'
    | '/admin/facilities'
    | '/admin/gallery'
    | '/admin/hero'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/ppdb'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/teachers'
    | '/admin/users'
    | '/announcements/$slug'
    | '/news/$slug'
    | '/news/announcements'
    | '/news/school'
    | '/profile/history'
    | '/profile/structure'
    | '/profile/vision'
    | '/admin/'
    | '/announcements/'
    | '/news/announcements/$slug'
    | '/news/announcements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/facilities'
    | '/gallery'
    | '/ppdb'
    | '/teachers'
    | '/admin/achievements'
    | '/admin/announcements'
    | '/admin/facilities'
    | '/admin/gallery'
    | '/admin/hero'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/ppdb'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/teachers'
    | '/admin/users'
    | '/announcements/$slug'
    | '/news/$slug'
    | '/news/school'
    | '/profile/history'
    | '/profile/structure'
    | '/profile/vision'
    | '/admin'
    | '/announcements'
    | '/news/announcements/$slug'
    | '/news/announcements'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/announcements'
    | '/facilities'
    | '/gallery'
    | '/ppdb'
    | '/teachers'
    | '/admin/achievements'
    | '/admin/announcements'
    | '/admin/facilities'
    | '/admin/gallery'
    | '/admin/hero'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/ppdb'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/teachers'
    | '/admin/users'
    | '/announcements/$slug'
    | '/news/$slug'
    | '/news/announcements'
    | '/news/school'
    | '/profile/history'
    | '/profile/structure'
    | '/profile/vision'
    | '/admin/'
    | '/announcements/'
    | '/news/announcements/$slug'
    | '/news/announcements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AnnouncementsRoute: typeof AnnouncementsRouteWithChildren
  FacilitiesRoute: typeof FacilitiesRoute
  GalleryRoute: typeof GalleryRoute
  PpdbRoute: typeof PpdbRoute
  TeachersRoute: typeof TeachersRoute
  AdminAchievementsRoute: typeof AdminAchievementsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminFacilitiesRoute: typeof AdminFacilitiesRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminPpdbRoute: typeof AdminPpdbRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsAnnouncementsRoute: typeof NewsAnnouncementsRouteWithChildren
  NewsSchoolRoute: typeof NewsSchoolRoute
  ProfileHistoryRoute: typeof ProfileHistoryRoute
  ProfileStructureRoute: typeof ProfileStructureRoute
  ProfileVisionRoute: typeof ProfileVisionRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppdb': {
      id: '/ppdb'
      path: '/ppdb'
      fullPath: '/ppdb'
      preLoaderRoute: typeof PpdbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/': {
      id: '/announcements/'
      path: '/'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AnnouncementsIndexRouteImport
      parentRoute: typeof AnnouncementsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/vision': {
      id: '/profile/vision'
      path: '/profile/vision'
      fullPath: '/profile/vision'
      preLoaderRoute: typeof ProfileVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/structure': {
      id: '/profile/structure'
      path: '/profile/structure'
      fullPath: '/profile/structure'
      preLoaderRoute: typeof ProfileStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/history': {
      id: '/profile/history'
      path: '/profile/history'
      fullPath: '/profile/history'
      preLoaderRoute: typeof ProfileHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/school': {
      id: '/news/school'
      path: '/news/school'
      fullPath: '/news/school'
      preLoaderRoute: typeof NewsSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/announcements': {
      id: '/news/announcements'
      path: '/news/announcements'
      fullPath: '/news/announcements'
      preLoaderRoute: typeof NewsAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/$slug': {
      id: '/announcements/$slug'
      path: '/$slug'
      fullPath: '/announcements/$slug'
      preLoaderRoute: typeof AnnouncementsSlugRouteImport
      parentRoute: typeof AnnouncementsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/admin/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ppdb': {
      id: '/admin/ppdb'
      path: '/admin/ppdb'
      fullPath: '/admin/ppdb'
      preLoaderRoute: typeof AdminPpdbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/admin/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/admin/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/admin/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/facilities': {
      id: '/admin/facilities'
      path: '/admin/facilities'
      fullPath: '/admin/facilities'
      preLoaderRoute: typeof AdminFacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/achievements': {
      id: '/admin/achievements'
      path: '/admin/achievements'
      fullPath: '/admin/achievements'
      preLoaderRoute: typeof AdminAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/announcements/': {
      id: '/news/announcements/'
      path: '/'
      fullPath: '/news/announcements/'
      preLoaderRoute: typeof NewsAnnouncementsIndexRouteImport
      parentRoute: typeof NewsAnnouncementsRoute
    }
    '/news/announcements/$slug': {
      id: '/news/announcements/$slug'
      path: '/$slug'
      fullPath: '/news/announcements/$slug'
      preLoaderRoute: typeof NewsAnnouncementsSlugRouteImport
      parentRoute: typeof NewsAnnouncementsRoute
    }
  }
}

interface AnnouncementsRouteChildren {
  AnnouncementsSlugRoute: typeof AnnouncementsSlugRoute
  AnnouncementsIndexRoute: typeof AnnouncementsIndexRoute
}

const AnnouncementsRouteChildren: AnnouncementsRouteChildren = {
  AnnouncementsSlugRoute: AnnouncementsSlugRoute,
  AnnouncementsIndexRoute: AnnouncementsIndexRoute,
}

const AnnouncementsRouteWithChildren = AnnouncementsRoute._addFileChildren(
  AnnouncementsRouteChildren,
)

interface NewsAnnouncementsRouteChildren {
  NewsAnnouncementsSlugRoute: typeof NewsAnnouncementsSlugRoute
  NewsAnnouncementsIndexRoute: typeof NewsAnnouncementsIndexRoute
}

const NewsAnnouncementsRouteChildren: NewsAnnouncementsRouteChildren = {
  NewsAnnouncementsSlugRoute: NewsAnnouncementsSlugRoute,
  NewsAnnouncementsIndexRoute: NewsAnnouncementsIndexRoute,
}

const NewsAnnouncementsRouteWithChildren =
  NewsAnnouncementsRoute._addFileChildren(NewsAnnouncementsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AnnouncementsRoute: AnnouncementsRouteWithChildren,
  FacilitiesRoute: FacilitiesRoute,
  GalleryRoute: GalleryRoute,
  PpdbRoute: PpdbRoute,
  TeachersRoute: TeachersRoute,
  AdminAchievementsRoute: AdminAchievementsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminFacilitiesRoute: AdminFacilitiesRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminPpdbRoute: AdminPpdbRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminUsersRoute: AdminUsersRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsAnnouncementsRoute: NewsAnnouncementsRouteWithChildren,
  NewsSchoolRoute: NewsSchoolRoute,
  ProfileHistoryRoute: ProfileHistoryRoute,
  ProfileStructureRoute: ProfileStructureRoute,
  ProfileVisionRoute: ProfileVisionRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
